local m = vim.keymap.set
local opts = { noremap = true, silent = true }

m("n", "<Leader>s", ":setlocal spell! spelllang=en_us<CR>")
m("n", "<Leader>x", ":silent !open %<CR>")
m("n", "<Leader>/", ":noh<CR>", opts)
m("n", "<Leader>b", ":bn<CR>")
m("n", "<Leader>B", ":bN<CR>")
m("n", "<Leader>v", "<C-^>")
m("n", "<Space>", ":")
m("n", "Q", "@q")
m("n", "<Leader>w", ":w<CR>")
m("n", "<Leader>q", ":q<CR>")
m("n", "<Leader>t", ":sp term://zsh<CR>i")
m("n", "<Leader>ev", ":e $MYVIMRC<CR>", opts)
m("n", "<Leader>sv", ":so $MYVIMRC<CR>", opts)
m("n", "<Leader>n", ":NERDTreeToggle<CR>")
m("n", "<Leader>m", ":ZenMode<CR>")
m("i", ",f", "=strftime('%F')<CR>")
m("n", "gf", ":e <cfile><CR>")
m("n", "<Leader>c", ":norm gcc<CR>")
m("n", "<C-p>", ":GFiles<CR>")
m("n", "<M-p>", ":Buffers<CR>")
m("n", "<C-f>", ":Files<CR>")
m("n", "<C-g>", ":Rg<CR>")
m("n", "<M-k>", ":m-2<CR>==")
m("n", "<M-j>", ":m+1<CR>==")
m("v", "<M-k>", ":m-2<CR>==")
m("v", "<M-j>", ":m+1<CR>==")
m("n", "<C-j>", "<C-w><C-j>")
m("n", "<C-k>", "<C-w><C-k>")
m("n", "<C-l>", "<C-w><C-l>")
m("n", "<C-h>", "<C-w><C-h>")
m("t", "<Esc>", "<C-\\><C-n>")
m("t", "<C-h>", "<C-\\><C-n><C-w>h")
m("t", "<C-j>", "<C-\\><C-n><C-w>j")
m("t", "<C-k>", "<C-\\><C-n><C-w>k")
m("t", "<C-l>", "<C-\\><C-n><C-w>l")
m("i", "<C-Space>", "<C-x><C-o>")
m("n", "<Leader>wi", "<nop>")
m("n", "<Leader>ww", "<nop>")
