local plug = vim.fn['plug#']

vim.call('plug#begin', '~/.vim/plugged')

plug('freeo/vim-kalisi')
plug('SirVer/ultisnips')
plug('honza/vim-snippets')
plug('gko/vim-coloresque', { ['for'] = {'css', 'scss', 'html'} })
plug('tpope/vim-surround')
plug('godlygeek/tabular')
plug('mattn/emmet-vim', { ['for'] = {'html', 'astro'} })
plug('scrooloose/nerdtree')
plug('Xuyuanp/nerdtree-git-plugin')
plug('tpope/vim-fugitive')
plug('airblade/vim-gitgutter')
plug('posva/vim-vue', { ['for'] = 'vue' })
plug('elixir-editors/vim-elixir', { ['for'] = 'elixir' })
plug('bakpakin/fennel.vim', { ['for'] = 'fennel' })
plug('vim-scripts/paredit.vim', { ['for'] = 'fennel' })
plug('zaid/vim-rec')
plug('NoahTheDuke/vim-just')
plug('andys8/vim-elm-syntax', { ['for'] = 'elm' })
plug('evanleck/vim-svelte', { ['for'] = 'svelte' })
plug('jparise/vim-graphql')
plug('easymotion/vim-easymotion')
plug('junegunn/fzf', { ['do'] = function() vim.fn['fzf#install']() end })
plug('junegunn/fzf.vim')
plug('glacambre/firenvim', { ['do'] = function() vim.fn['firenvim#install'](0) end })
plug('nvim-treesitter/nvim-treesitter')
plug('neovim/nvim-lspconfig')
plug('preservim/vim-markdown')
plug('folke/zen-mode.nvim')
plug('preservim/vim-pencil')
plug('EdenEast/nightfox.nvim')
plug('~/sandbox/tbls/vim-tbls')
plug('~/sandbox/vim-lil', { ['for'] = 'lil' })
plug('vimwiki/vimwiki')

vim.call('plug#end')
